import React from 'react';
import { ItemTypes } from './ItemTypes';


const CatalogOfProducts: ItemTypes[] =
  [
    {
      "id": 1,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-f/wc1000/6398330547.jpg'),
      "product_name": 'SYNERGETIC "Кокос и масло макадамии"',
      "size_type": "мл",
      "size": "380",
      "barcode": 4604049097548,
      "manufacturer": "Synergetic",
      "brand": "Synergetic",
      "description": "Гель для душа",
      "price": 199,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 2,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-l/wc1000/6375646161.jpg'),
      "product_name": "SYNERGETIC",
      "size_type": "мл",
      "size": "300",
      "barcode": 4604049097548,
      "manufacturer": "Synergetic",
      "brand": "Synergetic",
      "description": "Скраб для тела питание и тонус",
      "price": 254,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 3,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-d/wc1000/6368700637.jpg'),
      "product_name": 'SYNERGETIC "Карамельное яблоко и ваниль"',
      "size_type": "мл",
      "size": "450",
      "barcode": 4604049097548,
      "manufacturer": "Synergetic",
      "brand": "Synergetic",
      "description": "Натуральный крем для рук и тела",
      "price": 249,
      "care_type": ["Уход за телом", "Уход за руками"],
    },
    {
      "id": 4,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-5/wc1000/6558692645.jpg'),
      "product_name": "SYNERGETIC SPA",
      "size_type": "мл",
      "size": "75",
      "barcode": 4604049097548,
      "manufacturer": "Synergetic",
      "brand": "Synergetic",
      "description": "Натуральный крем для ног",
      "price": 169,
      "care_type": ["Уход за телом", "Уход за ногами"],
    },
    {
      "id": 5,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-q/wc1000/6335503358.jpg'),
      "product_name": "Bioderma Sebium Hydra ",
      "size_type": "мл",
      "size": "40",
      "barcode": 4604049097548,
      "manufacturer": "Bioderma",
      "brand": "Bioderma",
      "description": "Крем увлажняющий",
      "price": 1204,
      "care_type": ["Уход за лицом"],
    },
    {
      "id": 6,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-z/wc1000/6335515247.jpg'),
      "product_name": "Bioderma Sebium",
      "size_type": "мл",
      "size": "100",
      "barcode": 4604049097548,
      "manufacturer": "Bioderma",
      "brand": "Bioderma",
      "description": "Гель для умывания",
      "price": 648,
      "care_type": ["Уход за лицом"],
    },
    {
      "id": 7,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-q/wc1000/6335521286.jpg'),
      "product_name": "Bioderma Sensibio AR ",
      "size_type": "мл",
      "size": "40",
      "barcode": 4604049097548,
      "manufacturer": "Bioderma",
      "brand": "Bioderma",
      "description": "Увлажняющий крем для кожи",
      "price": 1647,
      "care_type": ["Уход за телом", "Уход за лицом"],
    },
    {
      "id": 8,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-g/wc1000/6335483116.jpg'),
      "product_name": "Bioderma Hydrabio",
      "size_type": "мл",
      "size": "250",
      "barcode": 4604049097548,
      "manufacturer": "Bioderma",
      "brand": "Bioderma",
      "description": "Тонизирующий увлажняющий лосьон",
      "price": 1860,
      "care_type": ["Уход за лицом"],
    },
    {
      "id": 9,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-f/wc1000/6394497195.jpg'),
      "product_name": "DUCRAY",
      "size_type": "мл",
      "size": "400",
      "barcode": 4604049097548,
      "manufacturer": "Ducray",
      "brand": "Ducray",
      "description": "Очищающий гель для лица и тела",
      "price": 1583,
      "care_type": ["Уход за телом", "Уход за лицом"],
    },
    {
      "id": 10,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-k/wc1000/6512837840.jpg'),
      "product_name": "DUCRAY Barrier Cream",
      "size_type": "мл",
      "size": "100",
      "barcode": 4604049097548,
      "manufacturer": "Ducray",
      "brand": "Ducray",
      "description": "Увлажняющий крем для сухой кожи",
      "price": 1856,
      "care_type": ["Уход за руками"],
    },
    {
      "id": 11,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-1/wc1000/6422796385.jpg'),
      "product_name": "DUCRAY ANACAPS PROGRESSIV",
      "size_type": "г",
      "size": "10",
      "barcode": 4604049097548,
      "manufacturer": "Ducray",
      "brand": "Ducray",
      "description": "Биологически активная добавка",
      "price": 1862,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 12,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-5/wc1000/6394496465.jpg'),
      "product_name": "DUCRAY",
      "size_type": "мл",
      "size": "30",
      "barcode": 4604049097548,
      "manufacturer": "Ducray",
      "brand": "Ducray",
      "description": "Сыворотка для лица",
      "price": 1511,
      "care_type": ["Уход за лицом"],
    },
    {
      "id": 13,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-f/wc1000/6283792587.jpg'),
      "product_name": "Johnson's Baby",
      "size_type": "мл",
      "size": "200",
      "barcode": 4604049097548,
      "manufacturer": "Johnson's Baby",
      "brand": "Johnson's Baby",
      "description": "Масло для тела с Алоэ",
      "price": 450,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 14,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-v/wc1000/6529427407.jpg'),
      "product_name": "JOHNSON Baby",
      "size_type": "мл",
      "size": "200",
      "barcode": 4604049097548,
      "manufacturer": "Johnson's Baby",
      "brand": "Johnson's Baby",
      "description": "Крем детский",
      "price": 847,
      "care_type": ["Уход за телом", "Уход за ногами"],
    },
    {
      "id": 15,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-5/wc1000/6559588865.jpg'),
      "product_name": "Johnson's",
      "size_type": "мл",
      "size": "300",
      "barcode": 4604049097548,
      "manufacturer": "Johnson's Baby",
      "brand": "Johnson's Baby",
      "description": "Гель для душа",
      "price": 460,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 16,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-k/wc1000/6563017556.jpg'),
      "product_name": "Johnson's",
      "size_type": "мл",
      "size": "300",
      "barcode": 4604049097548,
      "manufacturer": "Johnson's Baby",
      "brand": "Johnson's Baby",
      "description": "Увлажняющий лосьон",
      "price": 888,
      "care_type": ["Уход за телом"],
    },
    {
      "id": 17,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-1/wc1000/6270202357.jpg'),
      "product_name": "Vichy Purete Thermale",
      "size_type": "мл",
      "size": "150",
      "barcode": 4604049097548,
      "manufacturer": "VICHY",
      "brand": "VICHY",
      "description": "Очищающая пенка",
      "price": 1134,
      "care_type": ["Уход за лицом"],
    },
    {
      "id": 18,
      "image_url": new URL('https://ir.ozone.ru/s3/multimedia-p/wc1000/6588348109.jpg'),
      "product_name": "Vichy Liftactiv Supreme",
      "size_type": "мл",
      "size": "50",
      "barcode": 4604049097548,
      "manufacturer": "VICHY",
      "brand": "VICHY",
      "description": "Крем ночной",
      "price": 3911,
      "care_type": ["Уход за лицом"],
    }
  ]


export default CatalogOfProducts;